project:
  type: website

website:
  title: "Rohan Saklani"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true

execute:
  freeze: auto

